services:
  - type: web
    name: game-calendar-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    pythonVersion: 3.11.9
    envVars:
      - key: BOT_TOKEN
        sync: false
